#---- standalone 模式启动 ------
#server:
#  #如果不写，端口默认是8080
#  port: 8761
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}/eureka/

#--- 单机模拟双节点模式启动的eureka服务配置 ---
# 要修改 /etc/hosts
 #127.0.0.1 peer1
 #127.0.0.1 peer2
 #localhost peer1
 #localhost peer2

---
spring:
  profiles: peer1
  application:
    name: eureka-server1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka/

---
spring:
  profiles: peer2
  application:
    name: eureka-server2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/