eureka:
  client:
    service-url:
      #服务注册中心的默认地址
      defaultZone: http://peer1:8761/eureka/,http://peer1:8761/eureka/
    #作为微服务的客户端可以不注册到eureka
    register-with-eureka: false

  instance:
    #上次心跳发送多久后，这个实例被视为下线（默认90s,三个心跳时间）
    lease-expiration-duration-in-seconds: 90
    #向注册中心发送心跳消息的间隔(默认30s)
    lease-renewal-interval-in-seconds: 30
spring:
  application:
    name: service-client
server:
  port: 8081